savePrefix: ""

overrides:
  "@esbuild-kit/core-utils@3.3.2>esbuild": 0.25.12
  "protobufjs@8.0.1": 8.0.2

allowBuilds:
  better-sqlite3: true
  electron: true
  electron-winstaller: false
  esbuild: true
  node-pty: true
  protobufjs: true
  puppeteer: true
